// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api": {
            "get": {
                "tags": [
                    "App"
                ],
                "summary": "app route, get healthy status",
                "responses": {}
            }
        },
        "/api/v1/movies": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "get list of movies",
                "parameters": [
                    {
                        "enum": [
                            "created",
                            "imdb",
                            "year"
                        ],
                        "type": "string",
                        "description": "filter list movie",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pagination page_value, default 0",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/movies.MoviesEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/movies/search": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "get list of movies based on search query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query on movie name",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/movies.MoviesEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "movies.Movie": {
            "type": "object",
            "properties": {
                "classification": {},
                "comment": {
                    "type": "boolean"
                },
                "country": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "integer"
                            },
                            "title": {
                                "type": "string"
                            }
                        }
                    }
                },
                "cover": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "downloadas": {
                    "type": "string"
                },
                "duration": {},
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "integer"
                            },
                            "title": {
                                "type": "string"
                            }
                        }
                    }
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "imdb": {
                    "type": "number"
                },
                "playas": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "integer"
                            },
                            "quality": {
                                "type": "string"
                            },
                            "type": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        }
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "movies.MoviesEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/movies.MoviesResponseType"
                },
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "movies.MoviesResponseType": {
            "type": "object",
            "properties": {
                "movies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/movies.Movie"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
